name: Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      # Optional: only if your app is static export
      # - name: Export Next.js app
      #   run: npm run export

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}    # Your Web App name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} # From Azure Portal
          package: .
